### ISSUE TITLE
epicon: IPv6 support

### ISSUE THREAD

**Issue by jg1uaa** [kujiranodanna/IOT-House#10]
How about thinking IPv6 suport for epicon?
I just wrote  https://github.com/jg1uaa/IOT-House/commit/2f3c3af9eed9c445cceee03c714246fb67a1ac30 and at least working on OpenBSD. Testing on Linux is not yet.

Current implementation does not have IPv6->IPv4 (or vice versa) fallback, is this required for this project? (sometimes it may be a problem when "-n localhost", name resolution)

**Comment by kujiranodanna** [comment]
Since the original idea is simple is best, we do not plan to expand the function at this time. If verification is OK on Linux, please make a pull request.
