### ISSUE TITLE
epicon: memory(mem_buff) related problem

### ISSUE THREAD

**Issue by jg1uaa** [kujiranodanna/IOT-House#11]
problem report and remedy is committed to my repo, https://github.com/jg1uaa/IOT-House/commit/3e3245801ea384922624b57666565180060d060c (in IPv6 branch)

**Comment by kujiranodanna** [comment]
Thank you for reporting the bug. I'm sorry, but I can't scrutinize the content because I'm not the ability at the time of development. So if there is no verification problem, please update.
